version: '3'
services:
  app1:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - SERVER_ID=app1
    depends_on:
      - redis
  app2:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3002:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - SERVER_ID=app2
    depends_on:
      - redis
  app3:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3003:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - SERVER_ID=app3
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
