version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3
  app1:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - REDIS_URL=redis://redis:6379
      - SERVER_ID=app1
    depends_on:
      - redis
  app2:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - REDIS_URL=redis://redis:6379
      - SERVER_ID=app2
    depends_on:
      - redis
  app3:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - REDIS_URL=redis://redis:6379
      - SERVER_ID=app3
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
