version: '3'
services:
  app1:
    image: abdullah_rang/chat-app
    ports:
      - "3001:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - SERVER_ID=app1
    env_file:
      - env.list
    depends_on:
      - redis
  app2:
    image: abdullah_rang/chat-app
    ports:
      - "3002:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - SERVER_ID=app2
    env_file:
      - env.list
    depends_on:
      - redis
  app3:
    image: abdullah_rang/chat-app
    ports:
      - "3003:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - SERVER_ID=app3
    env_file:
      - env.list
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
